-- 1. Rename existing tables (keep backups)
ALTER TABLE RAW_TRANSACTIONS RENAME TO RAW_TRANSACTIONS_OLD;
ALTER TABLE SEGMENTED_CUSTOMERS RENAME TO SEGMENTED_CUSTOMERS_OLD;

-- 2. Create new RAW_TRANSACTIONS table (no TRANSACTION_ID, reordered)
CREATE OR REPLACE TABLE RAW_TRANSACTIONS (
    CUSTOMER_ID STRING,
    AMOUNT FLOAT,
    MERCHANT_CATEGORY STRING,
    TIMESTAMP TIMESTAMP
);

-- 3. Create new SEGMENTED_CUSTOMERS table (includes WINDOW_START, WINDOW_END)
CREATE OR REPLACE TABLE SEGMENTED_CUSTOMERS (
    WINDOW_START TIMESTAMP,
    WINDOW_END TIMESTAMP,
    CUSTOMER_ID STRING,
    TOTAL_SPENT FLOAT,
    AVG_TRANSACTION FLOAT,
    TRANSACTION_COUNT INT,
    SEGMENT STRING
);

-- 4. (Optional) Migrate any compatible data — update this if schema allows
-- For example, migrate RAW_TRANSACTIONS (ignoring TRANSACTION_ID)
INSERT INTO RAW_TRANSACTIONS (CUSTOMER_ID, AMOUNT, MERCHANT_CATEGORY, TIMESTAMP)
SELECT CUSTOMER_ID, AMOUNT, MERCHANT_CATEGORY, TIMESTAMP
FROM RAW_TRANSACTIONS_OLD;

-- SEGMENTED_CUSTOMERS likely not compatible unless WINDOW_START/END are added
-- If you want to populate from the old data, update this query accordingly:
-- INSERT INTO SEGMENTED_CUSTOMERS (...) SELECT ... FROM SEGMENTED_CUSTOMERS_OLD;

-- 5. (Optional & safe) Drop old tables after verification
-- DROP TABLE RAW_TRANSACTIONS_OLD;
-- DROP TABLE SEGMENTED_CUSTOMERS_OLD;
